package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cyverse-de/permissions/restapi/operations/permissions"
	"github.com/cyverse-de/permissions/restapi/operations/resource_types"
	"github.com/cyverse-de/permissions/restapi/operations/resources"
	"github.com/cyverse-de/permissions/restapi/operations/status"
	"github.com/cyverse-de/permissions/restapi/operations/subjects"
)

// NewPermissionsAPI creates a new Permissions instance
func NewPermissionsAPI(spec *loads.Document) *PermissionsAPI {
	return &PermissionsAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
		ServeError:      errors.ServeError,
		JSONConsumer:    runtime.JSONConsumer(),
		JSONProducer:    runtime.JSONProducer(),
		ResourceTypesDeleteResourceTypesIDHandler: resource_types.DeleteResourceTypesIDHandlerFunc(func(params resource_types.DeleteResourceTypesIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourceTypesDeleteResourceTypesID has not yet been implemented")
		}),
		StatusGetHandler: status.GetHandlerFunc(func(params status.GetParams) middleware.Responder {
			return middleware.NotImplemented("operation StatusGet has not yet been implemented")
		}),
		ResourceTypesGetResourceTypesHandler: resource_types.GetResourceTypesHandlerFunc(func(params resource_types.GetResourceTypesParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourceTypesGetResourceTypes has not yet been implemented")
		}),
		ResourceTypesPostResourceTypesHandler: resource_types.PostResourceTypesHandlerFunc(func(params resource_types.PostResourceTypesParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourceTypesPostResourceTypes has not yet been implemented")
		}),
		ResourceTypesPutResourceTypesIDHandler: resource_types.PutResourceTypesIDHandlerFunc(func(params resource_types.PutResourceTypesIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourceTypesPutResourceTypesID has not yet been implemented")
		}),
		ResourcesAddResourceHandler: resources.AddResourceHandlerFunc(func(params resources.AddResourceParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourcesAddResource has not yet been implemented")
		}),
		SubjectsAddSubjectHandler: subjects.AddSubjectHandlerFunc(func(params subjects.AddSubjectParams) middleware.Responder {
			return middleware.NotImplemented("operation SubjectsAddSubject has not yet been implemented")
		}),
		PermissionsBySubjectHandler: permissions.BySubjectHandlerFunc(func(params permissions.BySubjectParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsBySubject has not yet been implemented")
		}),
		PermissionsBySubjectAndResourceHandler: permissions.BySubjectAndResourceHandlerFunc(func(params permissions.BySubjectAndResourceParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsBySubjectAndResource has not yet been implemented")
		}),
		PermissionsBySubjectAndResourceTypeHandler: permissions.BySubjectAndResourceTypeHandlerFunc(func(params permissions.BySubjectAndResourceTypeParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsBySubjectAndResourceType has not yet been implemented")
		}),
		PermissionsCopyPermissionsHandler: permissions.CopyPermissionsHandlerFunc(func(params permissions.CopyPermissionsParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsCopyPermissions has not yet been implemented")
		}),
		ResourcesDeleteResourceHandler: resources.DeleteResourceHandlerFunc(func(params resources.DeleteResourceParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourcesDeleteResource has not yet been implemented")
		}),
		ResourcesDeleteResourceByNameHandler: resources.DeleteResourceByNameHandlerFunc(func(params resources.DeleteResourceByNameParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourcesDeleteResourceByName has not yet been implemented")
		}),
		ResourceTypesDeleteResourceTypeByNameHandler: resource_types.DeleteResourceTypeByNameHandlerFunc(func(params resource_types.DeleteResourceTypeByNameParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourceTypesDeleteResourceTypeByName has not yet been implemented")
		}),
		SubjectsDeleteSubjectHandler: subjects.DeleteSubjectHandlerFunc(func(params subjects.DeleteSubjectParams) middleware.Responder {
			return middleware.NotImplemented("operation SubjectsDeleteSubject has not yet been implemented")
		}),
		SubjectsDeleteSubjectByExternalIDHandler: subjects.DeleteSubjectByExternalIDHandlerFunc(func(params subjects.DeleteSubjectByExternalIDParams) middleware.Responder {
			return middleware.NotImplemented("operation SubjectsDeleteSubjectByExternalID has not yet been implemented")
		}),
		PermissionsGrantPermissionHandler: permissions.GrantPermissionHandlerFunc(func(params permissions.GrantPermissionParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsGrantPermission has not yet been implemented")
		}),
		PermissionsListPermissionsHandler: permissions.ListPermissionsHandlerFunc(func(params permissions.ListPermissionsParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsListPermissions has not yet been implemented")
		}),
		PermissionsListResourcePermissionsHandler: permissions.ListResourcePermissionsHandlerFunc(func(params permissions.ListResourcePermissionsParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsListResourcePermissions has not yet been implemented")
		}),
		ResourcesListResourcesHandler: resources.ListResourcesHandlerFunc(func(params resources.ListResourcesParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourcesListResources has not yet been implemented")
		}),
		SubjectsListSubjectsHandler: subjects.ListSubjectsHandlerFunc(func(params subjects.ListSubjectsParams) middleware.Responder {
			return middleware.NotImplemented("operation SubjectsListSubjects has not yet been implemented")
		}),
		PermissionsPutPermissionHandler: permissions.PutPermissionHandlerFunc(func(params permissions.PutPermissionParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsPutPermission has not yet been implemented")
		}),
		PermissionsRevokePermissionHandler: permissions.RevokePermissionHandlerFunc(func(params permissions.RevokePermissionParams) middleware.Responder {
			return middleware.NotImplemented("operation PermissionsRevokePermission has not yet been implemented")
		}),
		ResourcesUpdateResourceHandler: resources.UpdateResourceHandlerFunc(func(params resources.UpdateResourceParams) middleware.Responder {
			return middleware.NotImplemented("operation ResourcesUpdateResource has not yet been implemented")
		}),
		SubjectsUpdateSubjectHandler: subjects.UpdateSubjectHandlerFunc(func(params subjects.UpdateSubjectParams) middleware.Responder {
			return middleware.NotImplemented("operation SubjectsUpdateSubject has not yet been implemented")
		}),
	}
}

/*PermissionsAPI Manages Permissions for the CyVerse Discovery Environment and related applications. */
type PermissionsAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ResourceTypesDeleteResourceTypesIDHandler sets the operation handler for the delete resource types ID operation
	ResourceTypesDeleteResourceTypesIDHandler resource_types.DeleteResourceTypesIDHandler
	// StatusGetHandler sets the operation handler for the get operation
	StatusGetHandler status.GetHandler
	// ResourceTypesGetResourceTypesHandler sets the operation handler for the get resource types operation
	ResourceTypesGetResourceTypesHandler resource_types.GetResourceTypesHandler
	// ResourceTypesPostResourceTypesHandler sets the operation handler for the post resource types operation
	ResourceTypesPostResourceTypesHandler resource_types.PostResourceTypesHandler
	// ResourceTypesPutResourceTypesIDHandler sets the operation handler for the put resource types ID operation
	ResourceTypesPutResourceTypesIDHandler resource_types.PutResourceTypesIDHandler
	// ResourcesAddResourceHandler sets the operation handler for the add resource operation
	ResourcesAddResourceHandler resources.AddResourceHandler
	// SubjectsAddSubjectHandler sets the operation handler for the add subject operation
	SubjectsAddSubjectHandler subjects.AddSubjectHandler
	// PermissionsBySubjectHandler sets the operation handler for the by subject operation
	PermissionsBySubjectHandler permissions.BySubjectHandler
	// PermissionsBySubjectAndResourceHandler sets the operation handler for the by subject and resource operation
	PermissionsBySubjectAndResourceHandler permissions.BySubjectAndResourceHandler
	// PermissionsBySubjectAndResourceTypeHandler sets the operation handler for the by subject and resource type operation
	PermissionsBySubjectAndResourceTypeHandler permissions.BySubjectAndResourceTypeHandler
	// PermissionsCopyPermissionsHandler sets the operation handler for the copy permissions operation
	PermissionsCopyPermissionsHandler permissions.CopyPermissionsHandler
	// ResourcesDeleteResourceHandler sets the operation handler for the delete resource operation
	ResourcesDeleteResourceHandler resources.DeleteResourceHandler
	// ResourcesDeleteResourceByNameHandler sets the operation handler for the delete resource by name operation
	ResourcesDeleteResourceByNameHandler resources.DeleteResourceByNameHandler
	// ResourceTypesDeleteResourceTypeByNameHandler sets the operation handler for the delete resource type by name operation
	ResourceTypesDeleteResourceTypeByNameHandler resource_types.DeleteResourceTypeByNameHandler
	// SubjectsDeleteSubjectHandler sets the operation handler for the delete subject operation
	SubjectsDeleteSubjectHandler subjects.DeleteSubjectHandler
	// SubjectsDeleteSubjectByExternalIDHandler sets the operation handler for the delete subject by external Id operation
	SubjectsDeleteSubjectByExternalIDHandler subjects.DeleteSubjectByExternalIDHandler
	// PermissionsGrantPermissionHandler sets the operation handler for the grant permission operation
	PermissionsGrantPermissionHandler permissions.GrantPermissionHandler
	// PermissionsListPermissionsHandler sets the operation handler for the list permissions operation
	PermissionsListPermissionsHandler permissions.ListPermissionsHandler
	// PermissionsListResourcePermissionsHandler sets the operation handler for the list resource permissions operation
	PermissionsListResourcePermissionsHandler permissions.ListResourcePermissionsHandler
	// ResourcesListResourcesHandler sets the operation handler for the list resources operation
	ResourcesListResourcesHandler resources.ListResourcesHandler
	// SubjectsListSubjectsHandler sets the operation handler for the list subjects operation
	SubjectsListSubjectsHandler subjects.ListSubjectsHandler
	// PermissionsPutPermissionHandler sets the operation handler for the put permission operation
	PermissionsPutPermissionHandler permissions.PutPermissionHandler
	// PermissionsRevokePermissionHandler sets the operation handler for the revoke permission operation
	PermissionsRevokePermissionHandler permissions.RevokePermissionHandler
	// ResourcesUpdateResourceHandler sets the operation handler for the update resource operation
	ResourcesUpdateResourceHandler resources.UpdateResourceHandler
	// SubjectsUpdateSubjectHandler sets the operation handler for the update subject operation
	SubjectsUpdateSubjectHandler subjects.UpdateSubjectHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *PermissionsAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *PermissionsAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *PermissionsAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *PermissionsAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *PermissionsAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *PermissionsAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *PermissionsAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the PermissionsAPI
func (o *PermissionsAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ResourceTypesDeleteResourceTypesIDHandler == nil {
		unregistered = append(unregistered, "resource_types.DeleteResourceTypesIDHandler")
	}

	if o.StatusGetHandler == nil {
		unregistered = append(unregistered, "status.GetHandler")
	}

	if o.ResourceTypesGetResourceTypesHandler == nil {
		unregistered = append(unregistered, "resource_types.GetResourceTypesHandler")
	}

	if o.ResourceTypesPostResourceTypesHandler == nil {
		unregistered = append(unregistered, "resource_types.PostResourceTypesHandler")
	}

	if o.ResourceTypesPutResourceTypesIDHandler == nil {
		unregistered = append(unregistered, "resource_types.PutResourceTypesIDHandler")
	}

	if o.ResourcesAddResourceHandler == nil {
		unregistered = append(unregistered, "resources.AddResourceHandler")
	}

	if o.SubjectsAddSubjectHandler == nil {
		unregistered = append(unregistered, "subjects.AddSubjectHandler")
	}

	if o.PermissionsBySubjectHandler == nil {
		unregistered = append(unregistered, "permissions.BySubjectHandler")
	}

	if o.PermissionsBySubjectAndResourceHandler == nil {
		unregistered = append(unregistered, "permissions.BySubjectAndResourceHandler")
	}

	if o.PermissionsBySubjectAndResourceTypeHandler == nil {
		unregistered = append(unregistered, "permissions.BySubjectAndResourceTypeHandler")
	}

	if o.PermissionsCopyPermissionsHandler == nil {
		unregistered = append(unregistered, "permissions.CopyPermissionsHandler")
	}

	if o.ResourcesDeleteResourceHandler == nil {
		unregistered = append(unregistered, "resources.DeleteResourceHandler")
	}

	if o.ResourcesDeleteResourceByNameHandler == nil {
		unregistered = append(unregistered, "resources.DeleteResourceByNameHandler")
	}

	if o.ResourceTypesDeleteResourceTypeByNameHandler == nil {
		unregistered = append(unregistered, "resource_types.DeleteResourceTypeByNameHandler")
	}

	if o.SubjectsDeleteSubjectHandler == nil {
		unregistered = append(unregistered, "subjects.DeleteSubjectHandler")
	}

	if o.SubjectsDeleteSubjectByExternalIDHandler == nil {
		unregistered = append(unregistered, "subjects.DeleteSubjectByExternalIDHandler")
	}

	if o.PermissionsGrantPermissionHandler == nil {
		unregistered = append(unregistered, "permissions.GrantPermissionHandler")
	}

	if o.PermissionsListPermissionsHandler == nil {
		unregistered = append(unregistered, "permissions.ListPermissionsHandler")
	}

	if o.PermissionsListResourcePermissionsHandler == nil {
		unregistered = append(unregistered, "permissions.ListResourcePermissionsHandler")
	}

	if o.ResourcesListResourcesHandler == nil {
		unregistered = append(unregistered, "resources.ListResourcesHandler")
	}

	if o.SubjectsListSubjectsHandler == nil {
		unregistered = append(unregistered, "subjects.ListSubjectsHandler")
	}

	if o.PermissionsPutPermissionHandler == nil {
		unregistered = append(unregistered, "permissions.PutPermissionHandler")
	}

	if o.PermissionsRevokePermissionHandler == nil {
		unregistered = append(unregistered, "permissions.RevokePermissionHandler")
	}

	if o.ResourcesUpdateResourceHandler == nil {
		unregistered = append(unregistered, "resources.UpdateResourceHandler")
	}

	if o.SubjectsUpdateSubjectHandler == nil {
		unregistered = append(unregistered, "subjects.UpdateSubjectHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *PermissionsAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *PermissionsAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *PermissionsAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *PermissionsAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *PermissionsAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the permissions API
func (o *PermissionsAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *PermissionsAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/resource_types/{id}"] = resource_types.NewDeleteResourceTypesID(o.context, o.ResourceTypesDeleteResourceTypesIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = status.NewGet(o.context, o.StatusGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/resource_types"] = resource_types.NewGetResourceTypes(o.context, o.ResourceTypesGetResourceTypesHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/resource_types"] = resource_types.NewPostResourceTypes(o.context, o.ResourceTypesPostResourceTypesHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/resource_types/{id}"] = resource_types.NewPutResourceTypesID(o.context, o.ResourceTypesPutResourceTypesIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/resources"] = resources.NewAddResource(o.context, o.ResourcesAddResourceHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/subjects"] = subjects.NewAddSubject(o.context, o.SubjectsAddSubjectHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/permissions/subjects/{subject_type}/{subject_id}"] = permissions.NewBySubject(o.context, o.PermissionsBySubjectHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/permissions/subjects/{subject_type}/{subject_id}/{resource_type}/{resource_name}"] = permissions.NewBySubjectAndResource(o.context, o.PermissionsBySubjectAndResourceHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/permissions/subjects/{subject_type}/{subject_id}/{resource_type}"] = permissions.NewBySubjectAndResourceType(o.context, o.PermissionsBySubjectAndResourceTypeHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/permissions/subjects/{subject_type}/{subject_id}/copy"] = permissions.NewCopyPermissions(o.context, o.PermissionsCopyPermissionsHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/resources/{id}"] = resources.NewDeleteResource(o.context, o.ResourcesDeleteResourceHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/resources"] = resources.NewDeleteResourceByName(o.context, o.ResourcesDeleteResourceByNameHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/resource_types"] = resource_types.NewDeleteResourceTypeByName(o.context, o.ResourceTypesDeleteResourceTypeByNameHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/subjects/{id}"] = subjects.NewDeleteSubject(o.context, o.SubjectsDeleteSubjectHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/subjects"] = subjects.NewDeleteSubjectByExternalID(o.context, o.SubjectsDeleteSubjectByExternalIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/permissions"] = permissions.NewGrantPermission(o.context, o.PermissionsGrantPermissionHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/permissions"] = permissions.NewListPermissions(o.context, o.PermissionsListPermissionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/permissions/resources/{resource_type}/{resource_name}"] = permissions.NewListResourcePermissions(o.context, o.PermissionsListResourcePermissionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/resources"] = resources.NewListResources(o.context, o.ResourcesListResourcesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/subjects"] = subjects.NewListSubjects(o.context, o.SubjectsListSubjectsHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/permissions/resources/{resource_type}/{resource_name}/subjects/{subject_type}/{subject_id}"] = permissions.NewPutPermission(o.context, o.PermissionsPutPermissionHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/permissions/resources/{resource_type}/{resource_name}/subjects/{subject_type}/{subject_id}"] = permissions.NewRevokePermission(o.context, o.PermissionsRevokePermissionHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/resources/{id}"] = resources.NewUpdateResource(o.context, o.ResourcesUpdateResourceHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/subjects/{id}"] = subjects.NewUpdateSubject(o.context, o.SubjectsUpdateSubjectHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *PermissionsAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *PermissionsAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
