package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// BySubjectAndResourceURL generates an URL for the by subject and resource operation
type BySubjectAndResourceURL struct {
	ResourceName string
	ResourceType string
	SubjectID    string
	SubjectType  string

	Lookup   *bool
	MinLevel *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *BySubjectAndResourceURL) WithBasePath(bp string) *BySubjectAndResourceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *BySubjectAndResourceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *BySubjectAndResourceURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/permissions/subjects/{subject_type}/{subject_id}/{resource_type}/{resource_name}"

	resourceName := o.ResourceName
	if resourceName != "" {
		_path = strings.Replace(_path, "{resource_name}", resourceName, -1)
	} else {
		return nil, errors.New("ResourceName is required on BySubjectAndResourceURL")
	}
	resourceType := o.ResourceType
	if resourceType != "" {
		_path = strings.Replace(_path, "{resource_type}", resourceType, -1)
	} else {
		return nil, errors.New("ResourceType is required on BySubjectAndResourceURL")
	}
	subjectID := o.SubjectID
	if subjectID != "" {
		_path = strings.Replace(_path, "{subject_id}", subjectID, -1)
	} else {
		return nil, errors.New("SubjectID is required on BySubjectAndResourceURL")
	}
	subjectType := o.SubjectType
	if subjectType != "" {
		_path = strings.Replace(_path, "{subject_type}", subjectType, -1)
	} else {
		return nil, errors.New("SubjectType is required on BySubjectAndResourceURL")
	}
	_basePath := o._basePath
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var lookup string
	if o.Lookup != nil {
		lookup = swag.FormatBool(*o.Lookup)
	}
	if lookup != "" {
		qs.Set("lookup", lookup)
	}

	var minLevel string
	if o.MinLevel != nil {
		minLevel = *o.MinLevel
	}
	if minLevel != "" {
		qs.Set("min_level", minLevel)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *BySubjectAndResourceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *BySubjectAndResourceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *BySubjectAndResourceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on BySubjectAndResourceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on BySubjectAndResourceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *BySubjectAndResourceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
