package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cyverse-de/permissions/models"
)

// NewCopyPermissionsParams creates a new CopyPermissionsParams object
// with the default values initialized.
func NewCopyPermissionsParams() CopyPermissionsParams {
	var ()
	return CopyPermissionsParams{}
}

// CopyPermissionsParams contains all the bound params for the copy permissions operation
// typically these are obtained from a http.Request
//
// swagger:parameters copyPermissions
type CopyPermissionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The destination subjects.
	  Required: true
	  In: body
	*/
	DestSubjects *models.SubjectsIn
	/*The external subject identifier.
	  Required: true
	  In: path
	*/
	SubjectID string
	/*The subject type name.
	  Required: true
	  In: path
	*/
	SubjectType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CopyPermissionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.SubjectsIn
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("destSubjects", "body"))
			} else {
				res = append(res, errors.NewParseError("destSubjects", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.DestSubjects = &body
			}
		}

	} else {
		res = append(res, errors.Required("destSubjects", "body"))
	}

	rSubjectID, rhkSubjectID, _ := route.Params.GetOK("subject_id")
	if err := o.bindSubjectID(rSubjectID, rhkSubjectID, route.Formats); err != nil {
		res = append(res, err)
	}

	rSubjectType, rhkSubjectType, _ := route.Params.GetOK("subject_type")
	if err := o.bindSubjectType(rSubjectType, rhkSubjectType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CopyPermissionsParams) bindSubjectID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.SubjectID = raw

	return nil
}

func (o *CopyPermissionsParams) bindSubjectType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.SubjectType = raw

	if err := o.validateSubjectType(formats); err != nil {
		return err
	}

	return nil
}

func (o *CopyPermissionsParams) validateSubjectType(formats strfmt.Registry) error {

	if err := validate.Enum("subject_type", "path", o.SubjectType, []interface{}{"user", "group"}); err != nil {
		return err
	}

	return nil
}
