// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewListResourcePermissionsParams creates a new ListResourcePermissionsParams object
//
// There are no default values defined in the spec.
func NewListResourcePermissionsParams() ListResourcePermissionsParams {

	return ListResourcePermissionsParams{}
}

// ListResourcePermissionsParams contains all the bound params for the list resource permissions operation
// typically these are obtained from a http.Request
//
// swagger:parameters listResourcePermissions
type ListResourcePermissionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The resource name.
	  Required: true
	  In: path
	*/
	ResourceName string
	/*The resource type name.
	  Required: true
	  In: path
	*/
	ResourceType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListResourcePermissionsParams() beforehand.
func (o *ListResourcePermissionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rResourceName, rhkResourceName, _ := route.Params.GetOK("resource_name")
	if err := o.bindResourceName(rResourceName, rhkResourceName, route.Formats); err != nil {
		res = append(res, err)
	}

	rResourceType, rhkResourceType, _ := route.Params.GetOK("resource_type")
	if err := o.bindResourceType(rResourceType, rhkResourceType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindResourceName binds and validates parameter ResourceName from path.
func (o *ListResourcePermissionsParams) bindResourceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceName = raw

	return nil
}

// bindResourceType binds and validates parameter ResourceType from path.
func (o *ListResourcePermissionsParams) bindResourceType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceType = raw

	return nil
}
