package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// RevokePermissionURL generates an URL for the revoke permission operation
type RevokePermissionURL struct {
	ResourceName string
	ResourceType string
	SubjectID    string
	SubjectType  string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RevokePermissionURL) WithBasePath(bp string) *RevokePermissionURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RevokePermissionURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *RevokePermissionURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/permissions/resources/{resource_type}/{resource_name}/subjects/{subject_type}/{subject_id}"

	resourceName := o.ResourceName
	if resourceName != "" {
		_path = strings.Replace(_path, "{resource_name}", resourceName, -1)
	} else {
		return nil, errors.New("ResourceName is required on RevokePermissionURL")
	}
	resourceType := o.ResourceType
	if resourceType != "" {
		_path = strings.Replace(_path, "{resource_type}", resourceType, -1)
	} else {
		return nil, errors.New("ResourceType is required on RevokePermissionURL")
	}
	subjectID := o.SubjectID
	if subjectID != "" {
		_path = strings.Replace(_path, "{subject_id}", subjectID, -1)
	} else {
		return nil, errors.New("SubjectID is required on RevokePermissionURL")
	}
	subjectType := o.SubjectType
	if subjectType != "" {
		_path = strings.Replace(_path, "{subject_type}", subjectType, -1)
	} else {
		return nil, errors.New("SubjectType is required on RevokePermissionURL")
	}
	_basePath := o._basePath
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *RevokePermissionURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *RevokePermissionURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *RevokePermissionURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on RevokePermissionURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on RevokePermissionURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *RevokePermissionURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
