package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PermissionGrantRequest Information for granting permission to a user.
// swagger:model permission_grant_request
type PermissionGrantRequest struct {

	// permission level
	// Required: true
	PermissionLevel PermissionLevel `json:"permission_level"`

	// resource
	// Required: true
	Resource *ResourceIn `json:"resource"`

	// subject
	// Required: true
	Subject *SubjectIn `json:"subject"`
}

// Validate validates this permission grant request
func (m *PermissionGrantRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionLevel(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResource(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSubject(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionGrantRequest) validatePermissionLevel(formats strfmt.Registry) error {

	if err := m.PermissionLevel.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("permission_level")
		}
		return err
	}

	return nil
}

func (m *PermissionGrantRequest) validateResource(formats strfmt.Registry) error {

	if err := validate.Required("resource", "body", m.Resource); err != nil {
		return err
	}

	if m.Resource != nil {

		if err := m.Resource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource")
			}
			return err
		}
	}

	return nil
}

func (m *PermissionGrantRequest) validateSubject(formats strfmt.Registry) error {

	if err := validate.Required("subject", "body", m.Subject); err != nil {
		return err
	}

	if m.Subject != nil {

		if err := m.Subject.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subject")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PermissionGrantRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionGrantRequest) UnmarshalBinary(b []byte) error {
	var res PermissionGrantRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
