package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceTypesOut A list of resource types.
// swagger:model resource_types_out
type ResourceTypesOut struct {

	// The list of resource types.
	// Required: true
	ResourceTypes []*ResourceTypeOut `json:"resource_types"`
}

// Validate validates this resource types out
func (m *ResourceTypesOut) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceTypes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceTypesOut) validateResourceTypes(formats strfmt.Registry) error {

	if err := validate.Required("resource_types", "body", m.ResourceTypes); err != nil {
		return err
	}

	for i := 0; i < len(m.ResourceTypes); i++ {

		if swag.IsZero(m.ResourceTypes[i]) { // not required
			continue
		}

		if m.ResourceTypes[i] != nil {

			if err := m.ResourceTypes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resource_types" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourceTypesOut) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceTypesOut) UnmarshalBinary(b []byte) error {
	var res ResourceTypesOut
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
